/* E.Y.T B2B Cart / Checkout v1 */
const CART_KEY='EYT_B2B_CART_V1';
const money=n=>new Intl.NumberFormat('fa-IR').format(Number(n||0))+' ریال';
const safe=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function cartLoad(){try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{return[]}}
function cartSave(items){localStorage.setItem(CART_KEY,JSON.stringify(items));renderCart();}
function cartAdd(p,qty=1){if(!p?.productId) throw new Error('شناسه UUID محصول موجود نیست');const items=cartLoad();const i=items.findIndex(x=>x.productId===p.productId);if(i>=0)items[i].qty+=Number(qty);else items.push({productId:p.productId,productCode:p.productCode||'',name:p.nameFa||p.name||p.productName||'',qty:Number(qty)||1,unitPrice:Number(p.unitPrice||p.salePrice||0),minQuantity:Number(p.minQuantity||1)});cartSave(items)}
function cartRemove(id){cartSave(cartLoad().filter(x=>x.productId!==id))}
function cartQty(id,q){q=Math.max(1,Number(q)||1);cartSave(cartLoad().map(x=>x.productId===id?({...x,qty:q}):x))}
function cartTotal(){return cartLoad().reduce((s,x)=>s+x.qty*x.unitPrice,0)}
function injectCartStyles(){if(document.getElementById('eytCartStyles'))return;const s=document.createElement('style');s.id='eytCartStyles';s.textContent=`#eytCart{position:fixed;left:18px;bottom:18px;z-index:5000;font-family:Tahoma,Arial,sans-serif}.eyt-cart-toggle{border:0;border-radius:999px;background:#991b1b;color:#fff;padding:12px 17px;box-shadow:0 8px 30px #0003;cursor:pointer;font-weight:800}.eyt-cart-toggle span{background:#fff;color:#991b1b;border-radius:999px;padding:2px 7px;margin-right:5px}.eyt-cart-panel{display:none;position:absolute;left:0;bottom:52px;width:min(430px,calc(100vw - 36px));max-height:75vh;overflow:auto;background:#fff;border-radius:16px;padding:15px;box-shadow:0 15px 50px #0004}.eyt-cart-panel.open{display:block}.eyt-cart-head{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #e5e7eb;padding-bottom:10px;margin-bottom:10px}.eyt-cart-head button{border:0;background:#e5e7eb;border-radius:7px;font-size:18px;cursor:pointer}.eyt-cart-row{display:grid;grid-template-columns:1fr 72px 48px;gap:8px;align-items:center;border-bottom:1px solid #eee;padding:10px 0;font-size:12px}.eyt-cart-row input{width:72px;padding:7px}.eyt-cart-row button{border:0;background:#fee2e2;color:#991b1b;padding:7px;border-radius:6px;cursor:pointer}.eyt-cart-total{font-size:15px;padding:13px 0}.eyt-cart-panel textarea{width:100%;margin:5px 0;padding:9px;border:1px solid #d1d5db;border-radius:8px}.eyt-cart-panel #eytCheckout{width:100%;margin-top:8px}@media(max-width:520px){#eytCart{left:10px;bottom:10px}.eyt-cart-row{grid-template-columns:1fr 62px 42px}}`;document.head.appendChild(s)}
function cartUi(){if(document.getElementById('eytCart'))return;injectCartStyles();const el=document.createElement('div');el.id='eytCart';el.innerHTML=`<button id="eytCartToggle" class="eyt-cart-toggle">سبد سفارش <span id="eytCartCount">0</span></button><div id="eytCartPanel" class="eyt-cart-panel"><div class="eyt-cart-head"><b>سبد سفارش B2B</b><button id="eytCartClose">×</button></div><div id="eytCartItems"></div><div class="eyt-cart-total">جمع: <b id="eytCartTotal">0 ریال</b></div><textarea id="eytCartNotes" rows="2" placeholder="یادداشت سفارش"></textarea><button id="eytCheckout" class="btn primary">ثبت نهایی سفارش</button><div id="eytCartNotice"></div></div>`;document.body.appendChild(el);document.getElementById('eytCartToggle').onclick=()=>document.getElementById('eytCartPanel').classList.toggle('open');document.getElementById('eytCartClose').onclick=()=>document.getElementById('eytCartPanel').classList.remove('open');document.getElementById('eytCheckout').onclick=checkout;renderCart()}
function renderCart(){const items=cartLoad(),box=document.getElementById('eytCartItems');if(!box)return;document.getElementById('eytCartCount').textContent=new Intl.NumberFormat('fa-IR').format(items.reduce((s,x)=>s+x.qty,0));document.getElementById('eytCartTotal').textContent=money(cartTotal());box.innerHTML=items.length?items.map(x=>`<div class="eyt-cart-row"><div><b>${safe(x.productCode)}</b><div>${safe(x.name)}</div><small>${money(x.unitPrice)}</small></div><input type="number" min="1" value="${x.qty}" data-cart-qty="${safe(x.productId)}"><button data-cart-remove="${safe(x.productId)}">حذف</button></div>`).join(''):'<div class="muted">سبد خالی است.</div>';box.querySelectorAll('[data-cart-remove]').forEach(b=>b.onclick=()=>cartRemove(b.dataset.cartRemove));box.querySelectorAll('[data-cart-qty]').forEach(i=>i.onchange=()=>cartQty(i.dataset.cartQty,i.value))}
async function refreshCartPrices(){if(!window.EYT_CONFIG?.accessToken||!window.EYT_LIVE?.customerPrices)return;try{const prices=await window.EYT_LIVE.customerPrices({limit:500});const map=new Map((Array.isArray(prices)?prices:[]).map(p=>[String(p.productId),p]));const items=cartLoad().map(x=>{const p=map.get(String(x.productId));return p?{...x,unitPrice:Number(p.unitPrice??x.unitPrice),minQuantity:Number(p.minQuantity??x.minQuantity||1)}:x});cartSave(items)}catch(e){console.warn('EYT customer price refresh failed',e)}}
async function checkout(){const c=window.EYT_CONFIG||{},items=cartLoad(),notice=document.getElementById('eytCartNotice'),btn=document.getElementById('eytCheckout');if(!c.accessToken){notice.innerHTML='<div class="notice error">برای ثبت سفارش ابتدا وارد حساب مشتری شوید.</div>';return}if(!items.length){notice.innerHTML='<div class="notice error">سبد سفارش خالی است.</div>';return}btn.disabled=true;notice.innerHTML='<div class="notice local">در حال ثبت سفارش در Order Center...</div>';try{await refreshCartPrices();const finalItems=cartLoad();const key=crypto.randomUUID();const result=await window.EYT_LIVE.createLiveOrder({customerId:c.customerId,warehouseCode:c.warehouseCode||'MAIN',items:finalItems.map(x=>({product_id:x.productId,quantity:x.qty,unit_price:x.unitPrice})),notes:document.getElementById('eytCartNotes').value,idempotencyKey:key});localStorage.removeItem(CART_KEY);renderCart();notice.innerHTML=`<div class="notice live">سفارش <b>${safe(result.orderNo||result.order_no||'ثبت شد')}</b> با موفقیت ثبت شد.</div>`;if(result.orderNo||result.order_no)setTimeout(()=>document.getElementById('eytCartPanel').classList.remove('open'),900)}catch(e){notice.innerHTML=`<div class="notice error">${safe(e.message)}</div>`}finally{btn.disabled=false}}
function bindProductCards(){const host=document.getElementById('products');if(!host)return;host.querySelectorAll('.card').forEach(card=>{if(card.dataset.cartBound)return;const rawCode=card.dataset.productCode||card.querySelector('.product-code')?.textContent||card.querySelector('h3')?.textContent||'';const code=String(rawCode).trim();const id=card.dataset.productId||card.querySelector('[data-product-id]')?.dataset.productId||window.EYT_CONFIG?.productIds?.[code];if(!id)return;card.dataset.cartBound='1';card.dataset.productId=id;const price=Number(card.dataset.price||card.querySelector('[data-price]')?.dataset.price||0);const b=document.createElement('button');b.className='btn primary';b.type='button';b.textContent='افزودن به سبد';b.onclick=async()=>{try{if(window.EYT_CONFIG?.accessToken)await refreshCartPrices();const current=cartLoad().find(x=>x.productId===id);const livePrice=current?.unitPrice||price;cartAdd({productId:id,productCode:code,nameFa:card.querySelector('h3')?.textContent||code,unitPrice:livePrice,minQuantity:current?.minQuantity||1});document.getElementById('eytCartPanel').classList.add('open')}catch(e){alert(e.message)}};card.appendChild(b)})}
function bootCart(){cartUi();const host=document.getElementById('products');if(host)new MutationObserver(bindProductCards).observe(host,{childList:true,subtree:true});bindProductCards();window.addEventListener('eyt:customer-login',refreshCartPrices);window.EYT_CART={add:cartAdd,remove:cartRemove,items:cartLoad,total:cartTotal}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootCart,{once:true});else bootCart();
