/* E.Y.T B2B Cart / Checkout v1 */
const CART_KEY='EYT_B2B_CART_V1';
const money=n=>new Intl.NumberFormat('fa-IR').format(Number(n||0))+' ریال';
const safe=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function cartLoad(){try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{return[]}}
function cartSave(items){localStorage.setItem(CART_KEY,JSON.stringify(items));renderCart();}
function cartAdd(p,qty=1){if(!p?.productId) throw new Error('شناسه UUID محصول موجود نیست'); const items=cartLoad();const i=items.findIndex(x=>x.productId===p.productId); if(i>=0)items[i].qty+=Number(qty);else items.push({productId:p.productId,productCode:p.productCode||'',name:p.nameFa||p.name||p.productName||'',qty:Number(qty)||1,unitPrice:Number(p.unitPrice||p.salePrice||0),minQuantity:Number(p.minQuantity||1)});cartSave(items);}
function cartRemove(id){cartSave(cartLoad().filter(x=>x.productId!==id))}
function cartQty(id,q){q=Math.max(1,Number(q)||1);cartSave(cartLoad().map(x=>x.productId===id?({...x,qty:q}):x))}
function cartTotal(){return cartLoad().reduce((s,x)=>s+x.qty*x.unitPrice,0)}
function cartUi(){if(document.getElementById('eytCart'))return;const el=document.createElement('div');el.id='eytCart';el.innerHTML=`<button id="eytCartToggle" class="eyt-cart-toggle">سبد سفارش <span id="eytCartCount">0</span></button><div id="eytCartPanel" class="eyt-cart-panel"><div class="eyt-cart-head"><b>سبد سفارش B2B</b><button id="eytCartClose">×</button></div><div id="eytCartItems"></div><div class="eyt-cart-total">جمع: <b id="eytCartTotal">0 ریال</b></div><textarea id="eytCartNotes" rows="2" placeholder="یادداشت سفارش"></textarea><button id="eytCheckout" class="btn primary">ثبت نهایی سفارش</button><div id="eytCartNotice"></div></div>`;document.body.appendChild(el);document.getElementById('eytCartToggle').onclick=()=>document.getElementById('eytCartPanel').classList.toggle('open');document.getElementById('eytCartClose').onclick=()=>document.getElementById('eytCartPanel').classList.remove('open');document.getElementById('eytCheckout').onclick=checkout;renderCart();}
function renderCart(){const items=cartLoad(),box=document.getElementById('eytCartItems');if(!box)return;document.getElementById('eytCartCount').textContent=new Intl.NumberFormat('fa-IR').format(items.reduce((s,x)=>s+x.qty,0));document.getElementById('eytCartTotal').textContent=money(cartTotal());box.innerHTML=items.length?items.map(x=>`<div class="eyt-cart-row"><div><b>${safe(x.productCode)}</b><div>${safe(x.name)}</div><small>${money(x.unitPrice)}</small></div><input type="number" min="1" value="${x.qty}" data-cart-qty="${safe(x.productId)}"><button data-cart-remove="${safe(x.productId)}">حذف</button></div>`).join(''):'<div class="muted">سبد خالی است.</div>';box.querySelectorAll('[data-cart-remove]').forEach(b=>b.onclick=()=>cartRemove(b.dataset.cartRemove));box.querySelectorAll('[data-cart-qty]').forEach(i=>i.onchange=()=>cartQty(i.dataset.cartQty,i.value));}
async function checkout(){const c=window.EYT_CONFIG||{},items=cartLoad(),notice=document.getElementById('eytCartNotice'),btn=document.getElementById('eytCheckout');if(!c.accessToken){notice.innerHTML='<div class="notice error">برای ثبت سفارش ابتدا وارد حساب مشتری شوید.</div>';return}if(!items.length){notice.innerHTML='<div class="notice error">سبد سفارش خالی است.</div>';return}btn.disabled=true;notice.innerHTML='<div class="notice local">در حال ثبت سفارش در Order Center...</div>';try{const key=crypto.randomUUID();const result=await window.EYT_LIVE.createLiveOrder({customerId:c.customerId,warehouseCode:c.warehouseCode||'MAIN',items:items.map(x=>({product_id:x.productId,quantity:x.qty,unit_price:x.unitPrice})),notes:document.getElementById('eytCartNotes').value,idempotencyKey:key});localStorage.removeItem(CART_KEY);renderCart();notice.innerHTML=`<div class="notice live">سفارش <b>${safe(result.orderNo||result.order_no||'ثبت شد')}</b> با موفقیت ثبت شد.</div>`;if(result.orderNo||result.order_no)document.getElementById('eytCartPanel').classList.remove('open');}catch(e){notice.innerHTML=`<div class="notice error">${safe(e.message)}</div>`}finally{btn.disabled=false}}
function bindProductCards(){const host=document.getElementById('products');if(!host)return;host.querySelectorAll('.card').forEach(card=>{if(card.dataset.cartBound)return;const code=card.querySelector('.product-code')?.textContent?.trim()||card.dataset.productCode;const id=card.dataset.productId||card.querySelector('[data-product-id]')?.dataset.productId;if(!id)return;card.dataset.cartBound='1';const b=document.createElement('button');b.className='btn primary';b.textContent='افزودن به سبد';b.onclick=()=>{try{cartAdd({productId:id,productCode:code,nameFa:card.querySelector('h3')?.textContent||code,unitPrice:Number(card.dataset.price||0),minQuantity:1});document.getElementById('eytCartPanel').classList.add('open')}catch(e){alert(e.message)}};card.appendChild(b);});}
function bootCart(){cartUi();const host=document.getElementById('products');if(host)new MutationObserver(bindProductCards).observe(host,{childList:true,subtree:true});bindProductCards();window.EYT_CART={add:cartAdd,remove:cartRemove,items:cartLoad,total:cartTotal};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootCart,{once:true});else bootCart();
