-- E.Y.T ERP | PostgreSQL Schema v1.0
-- Master data + inventory + purchasing + sales + production + QC + warranty
-- UUIDs are generated by PostgreSQL. Business identifiers remain separate.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE organizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name varchar(200) NOT NULL,
  legal_name varchar(250),
  status varchar(30) NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE branches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id),
  code varchar(50) NOT NULL,
  name varchar(150) NOT NULL,
  city varchar(100),
  status varchar(30) NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, code)
);

CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id),
  username varchar(100) NOT NULL,
  full_name varchar(200),
  phone varchar(50),
  status varchar(30) NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, username)
);

CREATE TABLE warehouses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id uuid NOT NULL REFERENCES branches(id),
  code varchar(50) NOT NULL,
  name varchar(150) NOT NULL,
  warehouse_type varchar(40) NOT NULL DEFAULT 'general',
  status varchar(30) NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (branch_id, code)
);

CREATE TABLE locations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  warehouse_id uuid NOT NULL REFERENCES warehouses(id),
  code varchar(100) NOT NULL,
  name varchar(150),
  location_type varchar(40) NOT NULL DEFAULT 'bin',
  status varchar(30) NOT NULL DEFAULT 'active',
  UNIQUE (warehouse_id, code)
);

CREATE TABLE vehicle_brands (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name varchar(120) NOT NULL UNIQUE,
  country varchar(100),
  status varchar(30) NOT NULL DEFAULT 'active'
);

CREATE TABLE vehicle_models (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id uuid NOT NULL REFERENCES vehicle_brands(id),
  name varchar(120) NOT NULL,
  code varchar(80),
  status varchar(30) NOT NULL DEFAULT 'active',
  UNIQUE (brand_id, name)
);

CREATE TABLE vehicle_generations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  model_id uuid NOT NULL REFERENCES vehicle_models(id),
  name varchar(120) NOT NULL,
  start_year smallint,
  end_year smallint,
  status varchar(30) NOT NULL DEFAULT 'active',
  CHECK (end_year IS NULL OR start_year IS NULL OR end_year >= start_year)
);

CREATE TABLE vehicle_trims (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  generation_id uuid NOT NULL REFERENCES vehicle_generations(id),
  name varchar(120) NOT NULL,
  engine varchar(120),
  transmission varchar(80),
  status varchar(30) NOT NULL DEFAULT 'active'
);

CREATE TABLE product_categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id uuid REFERENCES product_categories(id),
  code varchar(80) NOT NULL UNIQUE,
  name varchar(150) NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'active'
);

CREATE TABLE products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sku varchar(80) NOT NULL UNIQUE,
  name varchar(200) NOT NULL,
  category_id uuid REFERENCES product_categories(id),
  product_type varchar(40) NOT NULL DEFAULT 'finished_good',
  unit varchar(30) NOT NULL DEFAULT 'pcs',
  brand varchar(100) DEFAULT 'E.Y.T',
  status varchar(30) NOT NULL DEFAULT 'active',
  min_stock numeric(18,3) NOT NULL DEFAULT 0,
  safety_stock numeric(18,3) NOT NULL DEFAULT 0,
  reorder_point numeric(18,3) NOT NULL DEFAULT 0,
  max_stock numeric(18,3),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (min_stock >= 0 AND safety_stock >= 0 AND reorder_point >= 0),
  CHECK (max_stock IS NULL OR max_stock >= reorder_point)
);

CREATE TABLE product_oem_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES products(id),
  oem_code varchar(120) NOT NULL,
  manufacturer varchar(120),
  is_primary boolean NOT NULL DEFAULT false,
  UNIQUE (product_id, oem_code)
);

CREATE TABLE product_barcodes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES products(id),
  barcode varchar(120) NOT NULL UNIQUE,
  barcode_type varchar(30) NOT NULL DEFAULT 'CODE128',
  is_primary boolean NOT NULL DEFAULT false
);

CREATE TABLE product_applications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES products(id),
  vehicle_trim_id uuid NOT NULL REFERENCES vehicle_trims(id),
  position varchar(80),
  side varchar(40),
  notes text,
  status varchar(30) NOT NULL DEFAULT 'active',
  UNIQUE (product_id, vehicle_trim_id, position, side)
);

CREATE TABLE boms (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES products(id),
  version varchar(30) NOT NULL,
  output_quantity numeric(18,3) NOT NULL DEFAULT 1,
  status varchar(30) NOT NULL DEFAULT 'draft',
  UNIQUE (product_id, version),
  CHECK (output_quantity > 0)
);

CREATE TABLE bom_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bom_id uuid NOT NULL REFERENCES boms(id) ON DELETE CASCADE,
  component_product_id uuid NOT NULL REFERENCES products(id),
  quantity numeric(18,6) NOT NULL,
  scrap_percent numeric(8,4) NOT NULL DEFAULT 0,
  UNIQUE (bom_id, component_product_id),
  CHECK (quantity > 0),
  CHECK (scrap_percent >= 0 AND scrap_percent <= 100)
);

CREATE TABLE operations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code varchar(80) NOT NULL UNIQUE,
  name varchar(150) NOT NULL,
  operation_type varchar(50) NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'active'
);

CREATE TABLE routings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES products(id),
  version varchar(30) NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'draft',
  UNIQUE (product_id, version)
);

CREATE TABLE routing_operations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  routing_id uuid NOT NULL REFERENCES routings(id) ON DELETE CASCADE,
  operation_id uuid NOT NULL REFERENCES operations(id),
  sequence_no integer NOT NULL,
  UNIQUE (routing_id, sequence_no)
);

CREATE TABLE suppliers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name varchar(200) NOT NULL,
  supplier_type varchar(50) NOT NULL,
  phone varchar(80),
  payment_terms varchar(120),
  credit_limit numeric(18,2) NOT NULL DEFAULT 0,
  status varchar(30) NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE supplier_products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL REFERENCES suppliers(id),
  product_id uuid NOT NULL REFERENCES products(id),
  supplier_sku varchar(120),
  last_price numeric(18,4),
  lead_time_days integer,
  UNIQUE (supplier_id, product_id)
);

CREATE TABLE purchase_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  request_no varchar(50) NOT NULL UNIQUE,
  requested_by uuid REFERENCES users(id),
  warehouse_id uuid REFERENCES warehouses(id),
  reason text,
  status varchar(30) NOT NULL DEFAULT 'draft',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE purchase_request_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_request_id uuid NOT NULL REFERENCES purchase_requests(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES products(id),
  quantity numeric(18,3) NOT NULL,
  required_date date,
  CHECK (quantity > 0)
);

CREATE TABLE purchase_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  po_no varchar(50) NOT NULL UNIQUE,
  supplier_id uuid NOT NULL REFERENCES suppliers(id),
  warehouse_id uuid REFERENCES warehouses(id),
  order_date date NOT NULL DEFAULT current_date,
  expected_date date,
  status varchar(30) NOT NULL DEFAULT 'draft',
  total_amount numeric(18,2) NOT NULL DEFAULT 0,
  prepayment_amount numeric(18,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (total_amount >= 0 AND prepayment_amount >= 0 AND prepayment_amount <= total_amount)
);

CREATE TABLE purchase_order_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_order_id uuid NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES products(id),
  quantity numeric(18,3) NOT NULL,
  unit_price numeric(18,4) NOT NULL,
  CHECK (quantity > 0 AND unit_price >= 0)
);

CREATE TABLE customers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_type varchar(50) NOT NULL,
  name varchar(200) NOT NULL,
  phone varchar(80),
  city varchar(100),
  credit_limit numeric(18,2) NOT NULL DEFAULT 0,
  status varchar(30) NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE dealer_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL UNIQUE REFERENCES customers(id),
  territory varchar(150),
  contract_no varchar(100),
  target_amount numeric(18,2) NOT NULL DEFAULT 0,
  status varchar(30) NOT NULL DEFAULT 'active'
);

CREATE TABLE sales_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_no varchar(50) NOT NULL UNIQUE,
  customer_id uuid NOT NULL REFERENCES customers(id),
  order_date date NOT NULL DEFAULT current_date,
  status varchar(30) NOT NULL DEFAULT 'draft',
  total_amount numeric(18,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sales_order_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sales_order_id uuid NOT NULL REFERENCES sales_orders(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES products(id),
  quantity numeric(18,3) NOT NULL,
  unit_price numeric(18,4) NOT NULL,
  discount numeric(18,2) NOT NULL DEFAULT 0,
  CHECK (quantity > 0 AND unit_price >= 0 AND discount >= 0)
);

CREATE TABLE batches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES products(id),
  batch_number varchar(100) NOT NULL UNIQUE,
  production_date date,
  supplier_id uuid REFERENCES suppliers(id),
  status varchar(30) NOT NULL DEFAULT 'active'
);

CREATE TABLE inventory_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES products(id),
  warehouse_id uuid NOT NULL REFERENCES warehouses(id),
  location_id uuid REFERENCES locations(id),
  batch_id uuid REFERENCES batches(id),
  qty_on_hand numeric(18,3) NOT NULL DEFAULT 0,
  qty_reserved numeric(18,3) NOT NULL DEFAULT 0,
  qty_qc_hold numeric(18,3) NOT NULL DEFAULT 0,
  UNIQUE (product_id, warehouse_id, location_id, batch_id),
  CHECK (qty_on_hand >= 0 AND qty_reserved >= 0 AND qty_qc_hold >= 0)
);

CREATE TABLE inventory_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES products(id),
  warehouse_id uuid NOT NULL REFERENCES warehouses(id),
  location_id uuid REFERENCES locations(id),
  batch_id uuid REFERENCES batches(id),
  transaction_type varchar(40) NOT NULL,
  quantity numeric(18,3) NOT NULL,
  reference_type varchar(60),
  reference_id uuid,
  created_by uuid REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (quantity <> 0)
);

CREATE TABLE inventory_reservations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES products(id),
  warehouse_id uuid NOT NULL REFERENCES warehouses(id),
  batch_id uuid REFERENCES batches(id),
  reference_type varchar(60) NOT NULL,
  reference_id uuid NOT NULL,
  quantity numeric(18,3) NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (quantity > 0)
);

CREATE TABLE stock_transfers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  transfer_no varchar(50) NOT NULL UNIQUE,
  from_warehouse_id uuid NOT NULL REFERENCES warehouses(id),
  to_warehouse_id uuid NOT NULL REFERENCES warehouses(id),
  status varchar(30) NOT NULL DEFAULT 'requested',
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (from_warehouse_id <> to_warehouse_id)
);

CREATE TABLE production_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_no varchar(50) NOT NULL UNIQUE,
  product_id uuid NOT NULL REFERENCES products(id),
  bom_id uuid REFERENCES boms(id),
  routing_id uuid REFERENCES routings(id),
  planned_qty numeric(18,3) NOT NULL,
  produced_qty numeric(18,3) NOT NULL DEFAULT 0,
  rejected_qty numeric(18,3) NOT NULL DEFAULT 0,
  start_date date,
  end_date date,
  status varchar(30) NOT NULL DEFAULT 'planned',
  CHECK (planned_qty > 0 AND produced_qty >= 0 AND rejected_qty >= 0)
);

CREATE TABLE production_operations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  production_order_id uuid NOT NULL REFERENCES production_orders(id) ON DELETE CASCADE,
  operation_id uuid NOT NULL REFERENCES operations(id),
  contractor_id uuid REFERENCES suppliers(id),
  planned_qty numeric(18,3) NOT NULL,
  completed_qty numeric(18,3) NOT NULL DEFAULT 0,
  rejected_qty numeric(18,3) NOT NULL DEFAULT 0,
  status varchar(30) NOT NULL DEFAULT 'planned',
  CHECK (planned_qty > 0 AND completed_qty >= 0 AND rejected_qty >= 0)
);

CREATE TABLE quality_inspections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  reference_type varchar(60) NOT NULL,
  reference_id uuid,
  product_id uuid NOT NULL REFERENCES products(id),
  batch_id uuid REFERENCES batches(id),
  inspection_type varchar(40) NOT NULL,
  result varchar(30) NOT NULL,
  inspected_by uuid REFERENCES users(id),
  inspection_date timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE non_conformances (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  inspection_id uuid REFERENCES quality_inspections(id),
  product_id uuid REFERENCES products(id),
  batch_id uuid REFERENCES batches(id),
  description text NOT NULL,
  root_cause text,
  status varchar(30) NOT NULL DEFAULT 'open',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE installations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES products(id),
  batch_id uuid REFERENCES batches(id),
  customer_id uuid REFERENCES customers(id),
  vehicle_trim_id uuid REFERENCES vehicle_trims(id),
  mechanic_name varchar(200),
  mechanic_phone varchar(80),
  installation_date date NOT NULL DEFAULT current_date,
  verification_code varchar(120),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE warranties (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES products(id),
  batch_id uuid REFERENCES batches(id),
  customer_id uuid REFERENCES customers(id),
  installation_id uuid REFERENCES installations(id),
  start_date date NOT NULL,
  end_date date,
  status varchar(30) NOT NULL DEFAULT 'active',
  CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE warranty_claims (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  warranty_id uuid NOT NULL REFERENCES warranties(id),
  claim_date date NOT NULL DEFAULT current_date,
  problem text NOT NULL,
  result text,
  resolution text,
  status varchar(30) NOT NULL DEFAULT 'open'
);

CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_product_applications_vehicle ON product_applications(vehicle_trim_id);
CREATE INDEX idx_inventory_product ON inventory_items(product_id);
CREATE INDEX idx_inventory_warehouse ON inventory_items(warehouse_id);
CREATE INDEX idx_inventory_transactions_product_date ON inventory_transactions(product_id, created_at);
CREATE INDEX idx_purchase_orders_supplier ON purchase_orders(supplier_id);
CREATE INDEX idx_sales_orders_customer ON sales_orders(customer_id);
CREATE INDEX idx_production_orders_product ON production_orders(product_id);
CREATE INDEX idx_quality_batch ON quality_inspections(batch_id);
CREATE INDEX idx_warranty_customer ON warranties(customer_id);

COMMENT ON TABLE products IS 'E.Y.T Product Master. Single source of truth for parts, materials, kits and finished goods.';
COMMENT ON TABLE product_applications IS 'Maps E.Y.T products to supported vehicle trims/applications.';
COMMENT ON TABLE inventory_transactions IS 'Immutable-style stock movement ledger. Corrections should be posted as compensating transactions.';
COMMENT ON TABLE production_operations IS 'Tracks internal or outsourced operations such as forging, CNC, machining and plating.';
